{% set name = "pytometry" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytometry-{{ version }}.tar.gz
  sha256: 8488a0d07019261203e32cd5b1819e9fe416cba17ca256756d60abbc15375c35

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.9
    - nbproject
    - numpy
    - pandas
    - anndata
    - scanpy
    - scipy
    - seaborn
    - matplotlib-base
    - readfcs >=1.1.0
    - datashader

test:
  imports:
    - pytometry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/buettnerlab/pytometry
  summary: Pytometry is a Python package for flow and mass cytometry analysis.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - berombau
