{% set name = "pytometry" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytometry-{{ version }}.tar.gz
  sha256: 16a5632c43b1800a0ad65f1ba98d6816724cfc1f3139b069fca15e4635513f90

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - nbproject
    - numpy
    - pandas
    - anndata
    - scanpy
    - scipy
    - seaborn
    - matplotlib-base
    - readfcs >=1.1.0
    - datashader

test:
  imports:
    - pytometry
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/buettnerlab/pytometry
  summary: Pytometry is a Python package for flow and mass cytometry analysis.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - berombau
